In [1]:
import numpy as np

In [3]:
alpha = np.array([0,1,2,3,4,5,6,7,8])
print("Dimention of alpha: ",alpha.ndim)

Dimention of alpha:  1


In [4]:
alpha=np.array([[1,2,3],[1,2,3]])
print("Dimention of alpha: ",alpha.ndim)

Dimention of alpha:  2


In [8]:
alpha = np.array([[[1, 2, 3], [1, 2, 3]],[[1, 2, 3], [1, 2, 3]]])
print("Dimention of alpha: ",alpha.ndim)

Dimention of alpha:  3


In [23]:
alpha = np.ones(((2,3)))
print("Dimention of alpha: ",alpha.ndim)
print(alpha)

Dimention of alpha:  2
[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
np.save('hello.npy',alpha)
print("saved")

saved


In [22]:
alpha=np.load('hello.npy')
print(alpha)

[[1. 1. 1.]
 [1. 1. 1.]]
