In [1]:
import numpy as np

c = np.array([
    [
        [1,2,3,4,5,6],
        [5,6,7,8,9,6],
        [9,10,11,12,8,6],
        [13,14,15,16,6,6],
        [17,18,19,20,4,7],
        [1,2,3,4,5,6]
    ],
    [
        [1,2,3,4,5,6],
        [5,6,7,8,9,8],
        [9,10,11,12,8,8],
        [13,14,15,16,6,8],
        [17,18,19,20,4,8],
        [1,2,3,4,5,6]
    ],
    [
        [1,2,3,4,5,5],
        [5,6,7,8,9,6],
        [9,10,11,12,8,6],
        [13,14,15,16,6,7],
        [17,18,19,20,8,4],
        [1,2,3,4,5,6]
    ],
    [
        [1,2,3,4,5,5],
        [5,6,7,8,9,7],
        [9,10,11,12,8,3],
        [13,14,15,16,6,2],
        [17,18,19,20,4,1],
        [1,2,3,4,5,6]
    ],
    [
        [1,2,3,4,5,3],
        [5,6,7,8,9,4],
        [9,10,11,12,8,5],
        [13,14,15,16,6,5],
        [17,18,19,20,4,3],
        [1,2,3,4,5,6]
    ],
    [
        [1,2,3,4,5,1],
        [5,6,7,8,9,1],
        [9,10,11,12,8,2],
        [13,14,15,3,16,6],
        [17,18,19,20,4,4],
        [1,2,3,4,5,6]
    ]
])

print(c)
print(c.shape)


[[[ 1  2  3  4  5  6]
  [ 5  6  7  8  9  6]
  [ 9 10 11 12  8  6]
  [13 14 15 16  6  6]
  [17 18 19 20  4  7]
  [ 1  2  3  4  5  6]]

 [[ 1  2  3  4  5  6]
  [ 5  6  7  8  9  8]
  [ 9 10 11 12  8  8]
  [13 14 15 16  6  8]
  [17 18 19 20  4  8]
  [ 1  2  3  4  5  6]]

 [[ 1  2  3  4  5  5]
  [ 5  6  7  8  9  6]
  [ 9 10 11 12  8  6]
  [13 14 15 16  6  7]
  [17 18 19 20  8  4]
  [ 1  2  3  4  5  6]]

 [[ 1  2  3  4  5  5]
  [ 5  6  7  8  9  7]
  [ 9 10 11 12  8  3]
  [13 14 15 16  6  2]
  [17 18 19 20  4  1]
  [ 1  2  3  4  5  6]]

 [[ 1  2  3  4  5  3]
  [ 5  6  7  8  9  4]
  [ 9 10 11 12  8  5]
  [13 14 15 16  6  5]
  [17 18 19 20  4  3]
  [ 1  2  3  4  5  6]]

 [[ 1  2  3  4  5  1]
  [ 5  6  7  8  9  1]
  [ 9 10 11 12  8  2]
  [13 14 15  3 16  6]
  [17 18 19 20  4  4]
  [ 1  2  3  4  5  6]]]
(6, 6, 6)


In [10]:
a=np.ones((3,2))
#3 is the row and 2 is the column
#ones is the inbuild function in the python it fill all values in the array is 1

In [11]:
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
b=np.zeros((3,2))
#3 is the row and 2 is the column
#Zeros is the inbuild function in the python it fill all values in the array is 0

In [13]:
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
np.random.random((2,3))
#2 is the row and 3 is the column
#random.random is the inbuild function in the python it fill the random values int he array

array([[0.19540585, 0.75661278, 0.54832048],
       [0.83464623, 0.75963534, 0.50727551]])

**#Advantages of the Numpy**

Faster Computation:                                                     
NumPy is faster than regular Python lists for mathematical operations.                        

Easy Operations:                                                  
You can perform operations on entire arrays without using loops.                                              

Handles Large Data:                                               
NumPy works well with large datasets, using less memory.                                

Works with Other Tools:                                                   
It integrates well with other Python libraries like pandas and TensorFlow.                                       

Many Functions:                                                       
NumPy provides a lot of built-in functions for calculations                                    

#Dis-Advantages of the Numpy

Steep Learning Curve:                       
It can be harder to learn compared to regular Python lists.                 

Same Data Type:                       
All elements in a NumPy array must be of the same type.                            

No GPU Support:                             
NumPy doesn't support GPU acceleration out of the box.                            

Handling Missing Data:                           
NumPy is not as good at handling missing data compared to other tools like pandas.                           

Less Flexible:                                                  
It's harder to add or remove elements in a NumPy array compared to a Python list.                             

In [4]:
import numpy as np
bita = np.array([[[1,2,3],[4,5,6]],
                 [[1,2,3],[4,5,6]],
                 [[1,2,3],[4,5,6]],
                 [[1,2,3],[4,5,6]]])
bita.shape
#4-
#2-
#3-

(4, 2, 3)

**Array with Range**

In [14]:
alpha=np.arange(60)
print(alpha) #

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [18]:
alpha.reshape(10,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [24]:
linspace_array=np.linspace(0,25,5)
print(linspace_array)

[ 0.    6.25 12.5  18.75 25.  ]


In [26]:
linspace_array=np.linspace(0,1,10)
print(linspace_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [40]:
import numpy as np

dfs = np.array([
    [2, 1, 2, 1],
    [3, 2, 6, 2],
    [4, 3, 2, 2],
    [8, 4, 6, 3]
])

In [41]:
dfs.shape

(4, 4)

In [50]:
dfs.sum(axis=0)

array([17, 10, 16,  8])

In [51]:
dfs.sum(axis=1)

array([ 6, 13, 11, 21])

In [52]:
dfs.min(axis=0)

array([2, 1, 2, 1])

In [53]:
dfs.min(axis=1)

array([1, 2, 2, 3])

In [54]:
dfs.max(axis=0)

array([8, 4, 6, 3])

In [45]:
dfs.max(axis=1)

array([2, 6, 4, 8])

In [48]:
dfs.mean(axis=0)

array([4.25, 2.5 , 4.  , 2.  ])

In [49]:
dfs.mean(axis=1)

array([1.5 , 3.25, 2.75, 5.25])

In [56]:
np.count_nonzero(dfs,axis=0)

array([4, 4, 4, 4])

In [57]:
np.count_nonzero(dfs,axis=1)

array([4, 4, 4, 4])